name: Train Model

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install mlflow pandas numpy scikit-learn joblib

      - name: Run MLflow Project
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          cd MLProject
          mlflow run . --env-manager local

      - name: Check Generated Model
        run: |
          echo "=== Saved Model ==="
          ls -lah MLProject/saved_model || true

          echo "=== Find model.pkl ==="
          find . -name "model.pkl"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/saved_model

      - name: Copy Model
        run: |
          cp MLProject/saved_model/model.pkl serving/model.pkl

      - name: Verify Serving Folder
        run: |
          echo "=== Serving Folder ==="
          ls -lah serving

      - name: Build Docker Image
        run: |
          docker build \
            -t telco-churn-model \
            ./serving

      - name: Tag Docker Image
        run: |
          docker tag telco-churn-model \
            ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest